version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - catflix_network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catflix_server
    ports:
      - "7071:7071"
    environment:
      - NODE_ENV=development
      - CONNECTION_STRING=mongodb://mongodb:27017/catflix
      - PORT=7071
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - catflix_network
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

networks:
  catflix_network:
    driver: bridge

volumes:
  mongodb_data: