version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - catflix_network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catflix_server
    ports:
      - "7071:7071"
    environment:
      - NODE_ENV=development
      - CONNECTION_STRING=mongodb://mongodb:27017/catflix
      - PORT=7071
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - catflix_network
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: catflix_web
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - API_URL=http://server:7071
    depends_on:
      - server
    restart: unless-stopped
    volumes:
      - ./part3:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app # Sets the working directory for the container
    command: "node app.js" # Explicitly runs 'app.js' from the mapped directory
    networks:
      - catflix_network

networks:
  catflix_network:
    driver: bridge

volumes:
  mongodb_data:
