services:
  server:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure it's using the correct Dockerfile for the C++ server
    container_name: catflix_server
    ports:
      - "7071:7071"  # Expose the server's port
    networks:
      - catflix_network

  client:
    build:
      context: .
      dockerfile: Dockerfile.client  # Ensure it's using the correct Dockerfile for the Python client
    networks:
      - catflix_network
    depends_on:
      - server
    entrypoint: ["python3", "client.py", "catflix_server", "7071"]
    stdin_open: true   # This allows interactive input
    tty: true          # This allocates a pseudo-TTY

networks:
  catflix_network:
    driver: bridge
