services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - catflix_network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpp_server
    ports:
      - "7071:7071"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/catflix
    depends_on:
      - mongodb
    networks:
      - catflix_network

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: catflix_web
    ports:
      - "8080:8080"
    environment:
      - CONNECTION_STRING=mongodb://mongodb:27017
      - PORT=8080
      - API_URL=http://server:7071
    depends_on:
      - server
    restart: unless-stopped
    volumes:
      - ./part3:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: "node app.js"
    networks:
      - catflix_network

networks:
  catflix_network:
    driver: bridge

volumes:
  mongodb_data:
