services:
  server:
    build:
      context: .
      dockerfile: Dockerfile  # Use the updated Dockerfile
    container_name: catflix_server
    ports:
      - "7071:7071"  # Expose the server's port
    networks:
      - catflix_network

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      - catflix_network
    depends_on:
      - server
    entrypoint: ["python3", "client.py", "catflix_server", "7071"]
    stdin_open: true   # Allows interactive input
    tty: true          # Allocates a pseudo-TTY

  tests:
    build:
      context: .
      dockerfile: Dockerfile  # Use the same Dockerfile that builds tests
    container_name: catflix_tests
    command: ["/Catflix/tests/test_runner"]  # Run the compiled test binary
    networks:
      - catflix_network
    depends_on:
      - server
    stdin_open: true   # Keep the stdin open
    tty: true

networks:
  catflix_network:
    driver: bridge
